name: Azure Pipelines
trigger: 
  - main
pool:
  name: myAgentPool
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: myAgentPool
    steps:
    #Needed for terraform VM deployment
   
    - task: TerraformInstaller@0
      inputs:
        version: '1.2.1'
      displayName: "Install Terraform 1.2.1"
    - task: InstallSSHKey@0
      displayName: Security Access
      inputs:
          knownHostsEntry: "|1|5uxN9dS2FZ4eUrPGF+urPR4loTc=|nDfA1gX5jG7D+aEx7XALqU3THT4= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF+pBcAMODB3R7i69QccHes+v0VTCBxmhwjPR+pTL+Fx5VXSjrJOLtHHW6Tnp/YHZ21jc1QHDSJkRfCVUA9c6og="
          sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC+GDJIACIJ8LfQrlix4roP29pxj48blXcJ9QKGh9g3oS5IDTK+KuQWeNtq82XrXFWAwdi0we94LEdL8CaVRIr2FkaEmjZkT9A73jHzXEqFBjpYGPWAW6+vbIr3OXa5Vhkgo6CPqymrFB37l87rNoWytXTgdWB94ahfj0vjLLixzsayTBtYRY8/8vIwLvPaBgf2C3mxlvgMnO2d6WcwfXNWtLjlGvoSIbOEcEyP6ylkknKNOsQZyFBSdBTE/p0WmUUc9VjtV3xoc+LBAEFFMiop9cquru7TJ095YFM1HGDus/8zWQuLFXCsZGQU/iVK2IaoqeFI3lZMe86D+BAvxj1 odl_user@cc-aed5dc39-8669c9c64-6j27k"
          sshKeySecureFile: 'id_rsa'
    - task: TerraformTaskV2@2 
      displayName: 'Initialize Terraform'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: 'myserviceconnection12312'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'storage12312'
        backendAzureRmContainerName: 'mycontainer123'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV1@0
      displayName: 'Validate Terraform'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test' 
        environmentServiceNameAzureRM: myserviceconnection12312
    - task: TerraformTaskV1@0
      displayName: 'Plan Terraform'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        commandOptions: '-var "public_key_path=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC+GDJIACIJ8LfQrlix4roP29pxj48blXcJ9QKGh9g3oS5IDTK+KuQWeNtq82XrXFWAwdi0we94LEdL8CaVRIr2FkaEmjZkT9A73jHzXEqFBjpYGPWAW6+vbIr3OXa5Vhkgo6CPqymrFB37l87rNoWytXTgdWB94ahfj0vjLLixzsayTBtYRY8/8vIwLvPaBgf2C3mxlvgMnO2d6WcwfXNWtLjlGvoSIbOEcEyP6ylkknKNOsQZyFBSdBTE/p0WmUUc9VjtV3xoc+LBAEFFMiop9cquru7TJ095YFM1HGDus/8zWQuLFXCsZGQU/iVK2IaoqeFI3lZMe86D+BAvxj1 odl_user@cc-aed5dc39-8669c9c64-6j27k"'
        environmentServiceNameAzureRM: myserviceconnection12312

    - task: TerraformTaskV1@0
      displayName: 'Apply Terraform'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        commandOptions: '-var "public_key_path=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC+GDJIACIJ8LfQrlix4roP29pxj48blXcJ9QKGh9g3oS5IDTK+KuQWeNtq82XrXFWAwdi0we94LEdL8CaVRIr2FkaEmjZkT9A73jHzXEqFBjpYGPWAW6+vbIr3OXa5Vhkgo6CPqymrFB37l87rNoWytXTgdWB94ahfj0vjLLixzsayTBtYRY8/8vIwLvPaBgf2C3mxlvgMnO2d6WcwfXNWtLjlGvoSIbOEcEyP6ylkknKNOsQZyFBSdBTE/p0WmUUc9VjtV3xoc+LBAEFFMiop9cquru7TJ095YFM1HGDus/8zWQuLFXCsZGQU/iVK2IaoqeFI3lZMe86D+BAvxj1 odl_user@cc-aed5dc39-8669c9c64-6j27k"'
        environmentServiceNameAzureRM: myserviceconnection12312
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload FakeRestAPI Package'
      artifact: drop-fakerestapi

    - publish: automatedtesting/selenium/login.py
      displayName: 'Upload UI Tests definition'
      artifact: drop-ui-tests